#!/bin/sh
#SBATCH --ntasks=64
#SBATCH --nodes=4
#SBATCH --partition=computeq
#SBATCH --time=00-12:00:00
#SBATCH --account=xshen1lab
#SBATCH --job-name=six_27
#SBATCH --mail-user=hgore@memphis.edu
#SBATCH --mem-per-cpu=6144
#SBATCH --output=OUTPUT_%j
#SBATCH --error=ERROR_%j
 
cd $SLURM_SUBMIT_DIR
 
echo "$SLURM_JOB_ID"
echo "$SLURM_ARRAY_JOB_ID"
echo "$SLURM_JOB_NODELIST"
 
java geneticalgorithm.genetic
